# This is a basic workflow to help you get started with Actions

name: Workflow dispatch

# Controls when the workflow will run
on:
  # Run every day at 5:55 UTC
  schedule:
    - cron: '55 5 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains two jobs called "Check" and "Update"
  Check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Output variables for next job
    outputs:
      current: ${{ steps.versions.outputs.current }}
      upstream: ${{ steps.versions.outputs.upstream }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Get latest Hekate release version
        id: versions
        run: >
          echo "upstream=$(
          curl
          -Ls
          -H 'Accept: application/vnd.github+json'
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
          -H 'X-GitHub-Api-Version: 2022-11-28'
          https://api.github.com/repos/CTCaer/hekate/releases?per_page=1
          |
          jq -r '.[0].tag_name'
          )" >> $GITHUB_OUTPUT;
          echo "current=$(cat version.txt)" >> $GITHUB_OUTPUT

  # Only run this job if needed
  Update:
    needs: Check
    if: needs.Check.outputs.current != needs.Check.outputs.upstream
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Install Python 3.12
        uses: actions/setup-python@main
        with:
          python-version: '3.14'

      - name: Get latest Hekate payload
        run: >
          curl
          -Ls
          -H 'Accept: application/vnd.github+json'
          -H 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}'
          -H 'X-GitHub-Api-Version: 2022-11-28'
          https://api.github.com/repos/CTCaer/hekate/releases?per_page=1
          |
          jq -r '.[0].assets[].browser_download_url | select(test("hekate_ctcaer_(?!.*__ram8GB).+\\.bin$"))'
          |
          xargs curl -LsO;
          mv *.bin payload.bin

      - name: Convert payload
        run: |
          python tx_custom_boot.py
          rm *.bin
          zip -m9 hekate_boot_dat_${{needs.Check.outputs.upstream}}.zip boot.dat

      - name: Update current version
        run: |
          echo ${{needs.Check.outputs.upstream}} > version.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add version.txt
          git commit -m "Updated version to ${{needs.Check.outputs.upstream}}"
          git tag -a ${{needs.Check.outputs.upstream}} -m ${{needs.Check.outputs.upstream}}
          git push origin ${{github.ref_name}} --tags

      - name: Create release
        run: |
          gh release create ${{needs.Check.outputs.upstream}} --title ${{needs.Check.outputs.upstream}} --notes "Updated version to ${{needs.Check.outputs.upstream}}" *.zip
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
